### ISSUE TITLE
新的PKURunner或导致本项目无法继续使用

### ISSUE THREAD

**Issue by HarsonLau** [PKUNoRun/PKUNoRun#1]
新的PKUrunner 版本1.2.7在上传数据时增加了abstract字段，不含abstract字段的记录上传不了。所以需要重新反编译一下新的PKUrunner

**Comment by HamiltonHuaji** [comment]
好的, 感谢反馈. 我抽空修改一下.

**Comment by HamiltonHuaji** [comment]
如果你能提供一份脱敏后的真实跑步记录就更好了. 你可以用sqlitebrowser等软件去除你的敏感信息.

**Comment by availableNengtao** [comment]
打开网站修改.db文件的时候一直提示Request fake data from server并一直没有修改成功

**Comment by HamiltonHuaji** [comment]
前面一段时间服务器迁移, 比较忙一直没来得及启动后端. 现在服务器应该是好的. 你再试试吧.

**Comment by CasparSwift** [comment]
刚才试了下 还是一直提示Request fake data from server...

**Comment by Yiran99** [comment]
> 刚才试了下 还是一直提示Request fake data from server...

是啊是啊 我这也是
