### ISSUE TITLE
上传数据时产生 Parse failed

### ISSUE THREAD

**Issue by YanWQ-monad** [PKUNoRun/PKUNoRun#15]
> 代发

PKURunner 在两星期前进行了一次更新，我查看了目前 sqlite 的结构，未发现变动。
目前虽无法上传，但在 PKURunner 里点击条目可以显示 fake record 的 track ，record 表如下所示：
（敏感数据已进行和谐，一个 `x` 代表一个数字）
|id|extra|date|detailed|distance|duration|invalidReason|photoName|photoRemotePath|placeHint|recordId|step|uploaded|userId|verified|
|--|--|--|--|--|--|--|--|--|--|--|--|--|--|--|
|1||163xxxxxxxxxx|0|xx|xx|7||||0|0|1|xx000xxxxx|0|
|2||163xxxxxxxxxx|1|6321.7|1675|0||||-1|4997|0|xx000xxxxx|1|
```
1||163xxxxxxxxxx|0|xx|xx|7||||0|0|1|xx000xxxxx|0
2||163xxxxxxxxxx|1|6321.7|1675|0||||-1|4997|0|xx000xxxxx|1
```
第一条为已经上传至服务器的测试记录。
第二条为无法上传的 fake record 。

使用方式：在已 root 的设备上将 `data.db` 、`data.db-shm` 与 `data.db-wal` pull 到本地，插入 fake 后重新 push 回到设备。
不使用 backup 的原因是无法成功备份（空 tar 包）。

![image](https://user-images.githubusercontent.com/20324409/133929648-3b7b0d78-5d9b-4d30-a137-4940a14940fd.png)

**Comment by potterandginny** [comment]
> > 代发
> 
> PKURunner 在两星期前进行了一次更新，我查看了目前 sqlite 的结构，未发现变动。
> 目前虽无法上传，但在 PKURunner 里点击条目可以显示 fake record 的 track ，record 表如下所示：
> （敏感数据已进行和谐，一个 `x` 代表一个数字）
> 
> id	extra	date	detailed	distance	duration	invalidReason	photoName	photoRemotePath	placeHint	recordId	step	uploaded	userId	verified
> 1		163xxxxxxxxxx	0	xx	xx	7				0	0	1	xx000xxxxx	0
> 2		163xxxxxxxxxx	1	6321.7	1675	0				-1	4997	0	xx000xxxxx	1
> ```
> 1||163xxxxxxxxxx|0|xx|xx|7||||0|0|1|xx000xxxxx|0
> 2||163xxxxxxxxxx|1|6321.7|1675|0||||-1|4997|0|xx000xxxxx|1
> ```
> 
> 第一条为已经上传至服务器的测试记录。
> 第二条为无法上传的 fake record 。
> 
> 使用方式：在已 root 的设备上将 `data.db` 、`data.db-shm` 与 `data.db-wal` pull 到本地，插入 fake 后重新 push 回到设备。
> 不使用 backup 的原因是无法成功备份（空 tar 包）。
> 
> ![image](https://user-images.githubusercontent.com/20324409/133929648-3b7b0d78-5d9b-4d30-a137-4940a14940fd.png)

请问为啥关了？求问方法~ 345598726@qq.com
