### ISSUE TITLE
修改上传data.db后无法上传记录

### ISSUE THREAD

**Issue by hegegit** [PKUNoRun/PKUNoRun#3]
修改上传data.db后，上传跑步记录时提示：与PKURunner服务器通讯失败：Incorrect Message Abstract

**Comment by hegegit** [comment]
runner官方的回复应该是版本问题

**Comment by HamiltonHuaji** [comment]
我无法重现这个问题. 我刚刚测试上传了一次是成功的. 你可以提供你的data.db吗?

**Comment by severus51950** [comment]
我也出现这个报错，与我用旧版本pkurunner跑步的报错相同

**Comment by severus51950** [comment]
我不知道怎么传我的data. db 或许我留一个qq小号吧 3457815502

**Comment by pansy116** [comment]
可以还把网站打开吗？很多手机导出data时不让选择使用pkurunner打开，只能保存微信分享

**Comment by HamiltonHuaji** [comment]
网站没关...我把删除线去掉免得误会好了. 微信分享然后用文件管理器打开也是可以分享到PKUNoRunHelper的吧.

**Comment by sakuanz** [comment]
求问大佬网站上传data.db之后，填好数据submit之后，一直转圈显示write data该怎么办

**Comment by HamiltonHuaji** [comment]
那恭喜你只是卡在最后一步了(x
好像这一步没啥网络请求，等就完事了(也许
或者你打开chrome/edge/firefox的开发者工具看看控制台有没有什么报错? 有的话就让我康康.

**Comment by HamiltonHuaji** [comment]
https://pkuhole.com/##11224
10939
这是跑步科技的报错
我舍友用旧版本的pkurunner正常跑步也报同样的错 更新之后就不报错了 怀疑是版本问题
（如果程序员无法复现报错的话 可否求个代刷 可有偿呜呜呜）
（10-22 15:27:31 5关注 16回复）
[Bob] Re 洞主: 截图一下版本号？
[洞主] Re : [图片]
[洞主] Re Bob: 官方好像是1.2.7？
[Alice] 更新一下就好了，必须在1.2.7以上才行

要不你们传不上去的试试最新版本…去release页面里找

**Comment by Yiran99** [comment]
谢谢大佬！我用新release+NoRunHelper成功了！
