### ISSUE TITLE
app-release.apk安装总是失败。。提示解析失败

### ISSUE THREAD

**Issue by JihangGao** [PKUNoRun/PKUNoRun#7]

**Comment by JihangGao** [comment]
解决了！谢谢

**Comment by HamiltonHuaji** [comment]
你怎么解决的?
我也遇到过别人装不上的情况, 你的经验也许可以作为参考.

**Comment by JihangGao** [comment]
> 你怎么解决的?
> 我也遇到过别人装不上的情况, 你的经验也许可以作为参考.

找了一个比较新的安卓手机，可能是安卓版本的问题...?我是用很旧的手机和模拟器都安装不了，借了同学的新手机成功的

**Comment by HamiltonHuaji** [comment]
好吧, 我以后用旧一点的sdk版本编译apk好了
